services:
  sing-box:
    image: darvyxe/sing-box:latest
    container_name: sing-box
    command: run -c /config/config.json
    volumes:
      - /opt/singbox:/config:ro
    restart: unless-stopped
    # ❌ ports حذف شد (CI-safe)

  db:
    image: postgres:15
    container_name: postgres_dayvpn
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dayvpn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  dayvpn-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dayvpn-bot
    environment:
      HTTP_PROXY: http://sing-box:7890
      HTTPS_PROXY: http://sing-box:7890
      http_proxy: http://sing-box:7890
      https_proxy: http://sing-box:7890

      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=dayvpn;Username=postgres;Password=${POSTGRES_PASSWORD}
      Redis__Host: redis:6379,password=${REDIS_PASSWORD},connectTimeout=10000,connectRetry=5,abortConnect=false
    depends_on:
      sing-box:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:80"
    restart: always

volumes:
  postgres_data:
  redis_data:
